import {BRIDGE_ID,rest} from './auth.ts';
function n(v,d=0){const x=Number(v);return Number.isFinite(x)?x:d;}function clamp(x,a,b){return Math.max(a,Math.min(b,x));}
function txSymbol(symbol){const code=symbol.slice(0,6);return symbol.endsWith('.SH')?'sh'+code:symbol.endsWith('.BJ')?'bj'+code:'sz'+code;}
async function fetchJson(url,timeoutMs=4200){const c=new AbortController(),to=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0','accept':'application/json,text/plain,*/*'},signal:c.signal,cache:'no-store'});if(!r.ok)throw new Error(`http ${r.status}`);return await r.json();}finally{clearTimeout(to);}}
function parseRows(raw){const out=[];for(const x of raw||[]){if(!Array.isArray(x)||x.length<6)continue;const open=n(x[1],NaN),close=n(x[2],NaN),high=n(x[3],NaN),low=n(x[4],NaN),volume=n(x[5],0);if([open,close,high,low].every(Number.isFinite)&&close>0)out.push({time:String(x[0]||''),open,close,high,low,volume});}return out;}
async function fetchPeriod(symbol,timeframe,count){const tx=txSymbol(symbol);if(timeframe==='day'){const u=`https://web.ifzq.gtimg.cn/appstock/app/fqkline/get?param=${encodeURIComponent(`${tx},day,,,${count},qfq`)}`;const j=await fetchJson(u),box=j?.data?.[tx]||{};return parseRows(box.qfqday||box.day||[]);}const key='m'+timeframe,u=`https://ifzq.gtimg.cn/appstock/app/kline/mkline?param=${encodeURIComponent(`${tx},${key},,${count}`)}`;const j=await fetchJson(u);return parseRows(j?.data?.[tx]?.[key]||[]);}
function ema(values,span){if(!values.length)return[];const a=2/(span+1),out=[values[0]];for(let i=1;i<values.length;i++)out.push(a*values[i]+(1-a)*out[i-1]);return out;}
function sign(x){return x>0?1:x<0?-1:0;}
function build(rows,timeframe){const fallback={ok:false,timeframe,label:'数据不足',score:0,state_score:0,transition_score:0,bars:rows.length};if(rows.length<35)return fallback;const close=rows.map(r=>r.close),e12=ema(close,12),e26=ema(close,26),dif=close.map((_,i)=>e12[i]-e26[i]),dea=ema(dif,9),hist=dif.map((d,i)=>2*(d-dea[i])),i=close.length-1,d=dif[i],a=dea[i],h=hist[i],hp=hist[i-1],hpp=hist[i-2],rel=d-a,scale=Math.max(Math.abs(d),Math.abs(a),Math.abs(h),Math.abs(close[i])*.0008,1e-9),difSlope=d-dif[i-1],deaSlope=a-dea[i-1],histDelta=h-hp,histAccel=(h-hp)-(hp-hpp),relSig=clamp(rel/(scale*.55),-1,1),histTrend=clamp(histDelta/(scale*.45),-1,1),difSlopeSig=clamp(difSlope/(scale*.32),-1,1),accelSig=clamp(histAccel/(scale*.40),-1,1),zeroSig=clamp(d/(scale*3.5),-1,1);let crossType='NONE',crossAge=null;for(let j=i;j>=Math.max(1,i-20);j--){const s0=sign(dif[j]-dea[j]),s1=sign(dif[j-1]-dea[j-1]);if(s0!==0&&s1!==0&&s0!==s1){crossType=s0>0?'GOLDEN':'DEAD';crossAge=i-j;break;}}let crossBoost=0;if(crossAge!==null&&crossAge<=3)crossBoost=(crossType==='GOLDEN'?1:-1)*(1-crossAge*.18);const transition=clamp(.45*histTrend+.30*accelSig+.25*crossBoost,-1,1),state=clamp(100*(.45*relSig+.20*histTrend+.18*difSlopeSig+.10*accelSig+.07*zeroSig),-100,100),near=Math.abs(d)<=scale*.35||Math.abs(a)<=scale*.35,zone=d>0&&a>0&&!near?'水上':d<0&&a<0&&!near?'水下':'零轴附近',histState=h>0?(h>hp?'红柱放大':'红柱缩短'):h<0?(Math.abs(h)>Math.abs(hp)?'绿柱放大':'绿柱缩短'):'柱体走平';let label=`${zone}·${histState}`;if(crossAge!==null&&crossAge<=3)label+=`·${crossType==='GOLDEN'?'金叉':'死叉'}${crossAge===0?'刚发生':crossAge+'根K'}`;return{ok:true,timeframe,label,pattern:label,zone,hist_state:histState,dif:d,dea:a,hist:h,dif_slope:difSlope,dea_slope:deaSlope,hist_delta:histDelta,hist_accel:histAccel,cross:crossType,cross_age_bars:crossAge,state_score:Math.round(state),transition_score:Number(transition.toFixed(4)),score:Math.round(state),bars:rows.length};}
function weekKey(s){const d=new Date(`${s}T00:00:00Z`);if(!Number.isFinite(d.getTime()))return s;const day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const y=new Date(Date.UTC(d.getUTCFullYear(),0,1)),w=Math.ceil((((d-y)/86400000)+1)/7);return `${d.getUTCFullYear()}-W${String(w).padStart(2,'0')}`;}
function aggregateWeek(rows){const map=new Map();for(const r of rows){const key=weekKey(String(r.time).slice(0,10)),old=map.get(key);if(!old)map.set(key,{time:key,open:r.open,close:r.close,high:r.high,low:r.low,volume:r.volume});else{old.close=r.close;old.high=Math.max(old.high,r.high);old.low=Math.min(old.low,r.low);old.volume+=r.volume;}}return [...map.values()];}
async function fresh(symbol){const jobs=[fetchPeriod(symbol,'1',240),fetchPeriod(symbol,'5',240),fetchPeriod(symbol,'15',220),fetchPeriod(symbol,'30',220),fetchPeriod(symbol,'60',220),fetchPeriod(symbol,'day',520)],res=await Promise.allSettled(jobs),get=i=>res[i].status==='fulfilled'?res[i].value:[],day=get(5),tf={m1:build(get(0),'1分钟'),m5:build(get(1),'5分钟'),m15:build(get(2),'15分钟'),m30:build(get(3),'30分钟'),m60:build(get(4),'60分钟'),day:build(day,'日线'),week:build(aggregateWeek(day),'周线')},weights={m1:.16,m5:.24,m15:.24,m30:.16,m60:.10,day:.07,week:.03};let sum=0,w=0,pos=0,neg=0;for(const [k,wt] of Object.entries(weights)){const s=tf[k];if(s?.ok){sum+=n(s.state_score)*wt;w+=wt;if(n(s.state_score)>=25)pos++;if(n(s.state_score)<=-25)neg++;}}const score=w?sum/w:0,bias=clamp(score/100,-1,1),summary=score>=55?'MACD多周期强多':score>=20?'MACD多周期偏强':score<=-55?'MACD多周期强空':score<=-20?'MACD多周期偏弱':'MACD周期分化',resonance=pos>=4?'多头共振':neg>=4?'空头共振':'周期分化';return{symbol,source:'腾讯公开K线',updated_at:new Date().toISOString(),score:Math.round(score),bias_score:bias,summary,resonance,timeframes:tf,calibration_version:'macd-structure-v9',monthly_provisional:false,weekly_provisional:true};}
export async function getMacdContext(symbol,force=false,refresh=true){const cached=await rest(`mobile_macd_cache?bridge_id=eq.${encodeURIComponent(BRIDGE_ID)}&symbol=eq.${encodeURIComponent(symbol)}&select=payload,updated_at&limit=1`),row=Array.isArray(cached)?cached[0]:null,age=row?.updated_at?Math.max(0,(Date.now()-Date.parse(row.updated_at))/1000):Infinity;if(!refresh)return row?.payload?{...row.payload,cache_age_seconds:age,freshness_seconds:age,cached:true,stale:age>=30}:{symbol,score:0,timeframes:{},freshness_seconds:999,summary:'MACD后台刷新中'};if(!force&&row?.payload&&age<30&&row.payload?.calibration_version==='macd-structure-v9')return{...row.payload,cache_age_seconds:age,freshness_seconds:age,cached:true};try{const payload=await fresh(symbol);await rest('mobile_macd_cache?on_conflict=bridge_id,symbol',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({bridge_id:BRIDGE_ID,symbol,payload,updated_at:payload.updated_at})});return{...payload,cache_age_seconds:0,freshness_seconds:0,cached:false};}catch(e){if(row?.payload)return{...row.payload,cache_age_seconds:age,freshness_seconds:age,cached:true,stale:true,error:'fresh_fetch_failed'};return{symbol,bias_score:0,score:0,summary:'MACD数据暂不可用',resonance:'--',timeframes:{},cache_age_seconds:null,freshness_seconds:999,error:String(e)};}}
