import {feedHealth} from './feed-health.ts';
const SUPABASE_URL = Deno.env.get('SUPABASE_URL') ?? '';
const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? Deno.env.get('SUPABASE_SERVICE_KEY') ?? '';
const BRIDGE_ID = 'family-qmt-01';
const ALLOWED_ORIGINS = new Set(['https://richard663-ui.github.io']);
const enc = new TextEncoder();

function b64url(a:ArrayBuffer|Uint8Array){ const u=a instanceof Uint8Array?a:new Uint8Array(a); let s=''; for(const b of u)s+=String.fromCharCode(b); return btoa(s).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_'); }
async function hmac(data:string){ const key=await crypto.subtle.importKey('raw',enc.encode(SERVICE_KEY),{name:'HMAC',hash:'SHA-256'},false,['sign']); return b64url(await crypto.subtle.sign('HMAC',key,enc.encode(data))); }
async function validSessionToken(t:string){ try{ const [p,s]=t.split('.'); if(!p||!s||s!==await hmac(p))return false; let x=p.replace(/-/g,'+').replace(/_/g,'/'); while(x.length%4)x+='='; return Number(JSON.parse(atob(x)).exp)>Date.now(); }catch{return false;} }
function cors(req:Request){ const origin=req.headers.get('origin')||''; if(!ALLOWED_ORIGINS.has(origin))return{}; return {'access-control-allow-origin':origin,'access-control-allow-methods':'GET,OPTIONS','access-control-allow-headers':'x-astock-session','access-control-max-age':'86400','vary':'Origin'}; }
function json(req:Request,data:unknown,status=200){ return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...cors(req)}}); }
async function rest(path:string){ const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:{apikey:SERVICE_KEY,authorization:`Bearer ${SERVICE_KEY}`}}); if(!r.ok)throw new Error(`db ${r.status}`); return JSON.parse(await r.text()); }
function n(v:unknown,d=0){ const x=Number(v); return Number.isFinite(x)?x:d; }
function arr(v:unknown){ return Array.isArray(v)?v.map(Number).filter(Number.isFinite):[]; }
function last<T>(a:T[]|null|undefined){ return Array.isArray(a)&&a.length?a[a.length-1]:null; }
function tickTs(t:any){ const raw=Number(t?.time); if(Number.isFinite(raw)&&raw>1e12)return raw; const p=Date.parse(String(t?.captured_at||'')); return Number.isFinite(p)?p:0; }
function windowTicks(ticks:any[],seconds:number){ if(!Array.isArray(ticks)||ticks.length<2)return ticks||[]; const end=tickTs(last(ticks)); if(end>0){ const p=ticks.filter(t=>tickTs(t)>0&&tickTs(t)>=end-seconds*1000); if(p.length>=2)return p; } return ticks.slice(Math.max(0,ticks.length-Math.max(2,seconds))); }
function best(t:any){ const bp=arr(t?.bidPrice),ap=arr(t?.askPrice),bv=arr(t?.bidVol),av=arr(t?.askVol); return {bid1:n(bp[0]??t?.bidPrice1,0),ask1:n(ap[0]??t?.askPrice1,0),bv1:n(bv[0]??t?.bidVol1,0),av1:n(av[0]??t?.askVol1,0)}; }
function bookPressure(t:any){ const bv=arr(t?.bidVol).slice(0,5),av=arr(t?.askVol).slice(0,5),w=[1,.78,.58,.40,.25]; let b=0,a=0; for(let i=0;i<5;i++){b+=(bv[i]||0)*w[i];a+=(av[i]||0)*w[i];} return b+a>0?100*b/(b+a):50; }
function avgBook(ticks:any[],seconds:number){ const p=windowTicks(ticks,seconds); return p.length?p.reduce((s,t)=>s+bookPressure(t),0)/p.length:50; }
function tradeFlow(ticks:any[],seconds:number){ const p=windowTicks(ticks,seconds); let buy=0,sell=0,events=0,prevSign=0; for(let i=1;i<p.length;i++){ const dv=Math.max(0,n(p[i]?.volume)-n(p[i-1]?.volume)); if(dv<=0)continue; events++; const price=n(p[i]?.lastPrice),prevPrice=n(p[i-1]?.lastPrice),q=best(p[i-1]); let sign=0; if(q.ask1>0&&price>=q.ask1)sign=1; else if(q.bid1>0&&price<=q.bid1)sign=-1; else if(price>prevPrice)sign=1; else if(price<prevPrice)sign=-1; else sign=prevSign; prevSign=sign; if(sign>0)buy+=dv; else if(sign<0)sell+=dv; } const total=buy+sell; return {buy_pct:total>0?100*buy/total:50,events,net:buy-sell}; }
function microBiasBp(t:any){ const q=best(t),price=n(t?.lastPrice,0); if(!(price>0&&q.bid1>0&&q.ask1>0&&q.bv1+q.av1>0))return null; const mp=(q.ask1*q.bv1+q.bid1*q.av1)/(q.bv1+q.av1); return (mp/price-1)*10000; }
function volumeBurst(ticks:any[]){ const p60=windowTicks(ticks,60),p15=windowTicks(ticks,15); if(p60.length<2||p15.length<2)return null; const end=last(ticks),tEnd=tickTs(end),t60=tickTs(p60[0]),t15=tickTs(p15[0]); if(!(tEnd>t60&&tEnd>t15))return null; const vEnd=n(end?.volume),v60=n(p60[0]?.volume),v15=n(p15[0]?.volume),dv60=Math.max(0,vEnd-v60),dv15=Math.max(0,vEnd-v15),d60=(tEnd-t60)/1000,d15=(tEnd-t15)/1000,priorDur=d60-d15,priorVol=Math.max(0,dv60-dv15); if(d15<5||priorDur<10)return null; const recent=dv15/d15,prior=priorVol/priorDur; return prior>0?recent/prior:null; }
function coverage(ticks:any[]){ if(ticks.length<2)return 0; const a=tickTs(ticks[0]),b=tickTs(last(ticks)); return a>0&&b>=a?(b-a)/1000:0; }

Deno.serve(async(req:Request)=>{ try{ if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)}); if(!(await validSessionToken(req.headers.get('x-astock-session')||'')))return json(req,{error:'unauthorized'},401); const watch=await rest(`qmt_watch_requests?bridge_id=eq.${encodeURIComponent(BRIDGE_ID)}&select=symbol&limit=1`),symbol=(Array.isArray(watch)&&watch[0]?.symbol)||'000400.SZ',liveRows=await rest(`qmt_live_cache?bridge_id=eq.${encodeURIComponent(BRIDGE_ID)}&symbol=eq.${encodeURIComponent(symbol)}&select=updated_at,ticks&limit=1`),live=Array.isArray(liveRows)?liveRows[0]:null,ticks=Array.isArray(live?.ticks)?live.ticks:[],latest=last(ticks)||{},updated=live?.updated_at?Date.parse(live.updated_at):0,stale=Math.max(0,(Date.now()-updated)/1000),flow20=tradeFlow(ticks,20),flow60=tradeFlow(ticks,60),bp=avgBook(ticks,12),prior35=windowTicks(ticks,35),recent12=windowTicks(ticks,12),prior=prior35.length>recent12.length?prior35.slice(0,Math.max(1,prior35.length-recent12.length)):prior35,priorBp=prior.length?prior.reduce((s,t)=>s+bookPressure(t),0)/prior.length:bp; return json(req,{ok:true,symbol,...feedHealth(live),coverage_seconds:coverage(ticks),active_buy_estimate_20s_pct:flow20.buy_pct,active_buy_estimate_60s_pct:flow60.buy_pct,trade_events_20s:flow20.events,trade_events_60s:flow60.events,book_pressure_12s_pct:bp,book_pressure_change_pct:bp-priorBp,microprice_bias_bp:microBiasBp(latest),volume_burst_ratio:volumeBurst(ticks),source:'QMT tick estimate; not true Level-2'}); }catch(e){ return json(req,{error:'temporary backend error',detail:String(e instanceof Error?e.message:e)},500); } });
